language: go

os:
  - linux

env:
  global:
    - GO111MODULE=off

addons:
  apt:
    packages:
      - zip

install:
  - make setup

script:
  - make all

deploy:
  provider: releases
  api_key:
    secure: cykWxW7IlAWkB0EyM2HQRN8VlNSbOgRml9X/0rJWcExf3DXj7QC8nA6sT04vrD+0TChFIxAcCQM375U9uPy3mMz66ud1IjADvrASvUrE/2K5EozADocTtSvnZXcH1Yxk3iNvDDVGgBtWR6J31JXzKxd1Tx4RgHBRxOvttl+UwHm8gpw7WDf1tBeTy9gLs6Wpzc5Nd3oLW8h4J24uTc+TAw5CRb2+df0TDdTC9Zqt9x0H2qekE1jyyHFGvI3KAFxV1kt5T8Ims8faFiYQqxW0EGsdy8Y7AUij7y0oDSf/QU4v3evcDAvLOKKLW9u/95Qpe7XjPDf75DeJdO9vWMBoMGOCqdrlcPfNrM5qizTAdGhMQvkASA+qWwTtX1j8QtueoWTwMz1/0IH7gRgThPK9cIdVF/fyhzcGJX73LKTthSOniTV0G8RTvZudjuJV7/qDxn1P2NxJCG7E6J0KpBTEBRdSQDQhS4aQyxO1E7gCrLIzrsOzDUp4+tfG+wQpT/0ycHTuTT0spYGDi4ASn676qKE8GRBIq4ySvWxqVjY9rwF3YTbVc3Izv30K6xc5d5qgNTc+g4oAzpqr6UrUR3MxC9kEbb+Sdmpsin+/6/UIdyqx5HG8Hv4QaSGFNTEqrgljlKZQ7sU0OoSTI4+uLHZk1UvCCOdWRkvDVSMpbUg5Y68=
  keep-history: false
  skip_cleanup: true
  file_glob: true
  file: 'dist/*.zip'
  on:
    tags: true
