[image]
# 保存するファイル名の書式
save_filename_format = "actor%03d.png"

# 画像の組み合わせ
# 一番上のファイルに順に重ねるように画像を貼り付けていく。
pattern = [

# 1P
# ------------------------------------------------------------------------------
# 通常
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/normal.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/normal.png",
    "target/actor022/diff/option/red.png"
  ],
# 会話
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/normal.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/smile.png",
    "target/actor022/diff/option/red.png"
  ],
# 驚き
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/surprise.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/talk.png",
    "target/actor022/diff/option/red.png"
  ],
# 無表情
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/normal.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/nan.png",
    "target/actor022/diff/option/red.png"
  ],
# 喜
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/smile.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/smile.png",
    "target/actor022/diff/option/red.png"
  ],
# 怒
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/normal.png",
    "target/actor022/diff/eyebrows/angry.png",
    "target/actor022/diff/mouse/shout.png",
    "target/actor022/diff/option/red.png"
  ],
# 哀
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/normal.png",
    "target/actor022/diff/eyebrows/sad.png",
    "target/actor022/diff/mouse/talk.png",
    "target/actor022/diff/option/red.png"
  ],
# 楽
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/smile.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/normal.png",
    "target/actor022/diff/option/red.png"
  ],

# 2P
# ------------------------------------------------------------------------------
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/close.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/normal.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/close.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/smile.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/close.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/talk.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/close.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/nan.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/close.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/shout.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/normal.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/smile.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/talk.png",
    "target/actor022/diff/option/red.png"
  ],

# 3P
# ------------------------------------------------------------------------------
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/nan.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/normal.png",
    "target/actor022/diff/mouse/shout.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/angry.png",
    "target/actor022/diff/mouse/normal.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/angry.png",
    "target/actor022/diff/mouse/smile.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/angry.png",
    "target/actor022/diff/mouse/talk.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/angry.png",
    "target/actor022/diff/mouse/nan.png",
    "target/actor022/diff/option/red.png"
  ],
  [
    "target/actor022/diff/body/normal.png",
    "target/actor022/diff/eye/jito.png",
    "target/actor022/diff/eyebrows/angry.png",
    "target/actor022/diff/mouse/shout.png",
    "target/actor022/diff/option/red.png"
  ]

]
